### ISSUE TITLE
现在还能用吗 好像报错了...

### ISSUE THREAD

**Issue by smallwhitedesu1** [zhuweitung/banana-helper#3]
**错误描述**

> 2023-03-05 02:22:56 INFO  : 2023-03-05 02:22:56
2023-03-05 02:22:56 DEBUG : 任务启动中...
2023-03-05 02:22:56 INFO  : ------开始给Acer new个对象------
2023-03-05 02:22:56 DEBUG : 请求获取账号信息接口出错，请稍后重试。错误请求信息：
{"result":-401,"error_msg":"user not login"}

**使用版本**

> 0.2.12

**使用环境**

> Windows Server 2012 R2 Datacenter

**日志输出**

> 2023-03-05 02:22:55 INFO  : 未扫描到外部配置文件，即将加载默认配置文件【此提示仅
针自行部署的Linux用户，普通用户请忽略】
2023-03-05 02:22:55 INFO  : 读取内部配置文件成功
2023-03-05 02:22:55 INFO  : 配置信息 {每日投蕉数为：30；投蕉并点赞：是；投蕉并发
送弹幕：是；是否点赞：是；是否发送弹幕：是；弹幕优先级为：视频弹幕池频率最高；弹
幕池为：[]；是否分享：是；投蕉策略为：每日香蕉榜优先；关注up的投蕉优先级为：[]；
跳过投蕉点赞弹幕up列表为：[]}
2023-03-05 02:22:56 DEBUG : 请求获取TOKEN接口出错，请稍后重试。错误请求信息：{"r
esult":-401,"error_msg":"token value error"}
2023-03-05 02:22:56 INFO  : -----项目信息-----
2023-03-05 02:22:56 INFO  : 当前版本: 0.2.12
2023-03-05 02:22:56 INFO  : 最后更新日期: 2022-09-06
2023-03-05 02:22:56 INFO  : 项目开源地址: https://github.com/zhuweitung/banana-h
elper.git
2023-03-05 02:22:56 INFO  : AcFun主页: https://www.acfun.cn/u/625724
2023-03-05 02:22:56 INFO  : -----项目信息-----

2023-03-05 02:22:56 INFO  : 2023-03-05 02:22:56
2023-03-05 02:22:56 DEBUG : 任务启动中...
2023-03-05 02:22:56 INFO  : ------开始给Acer new个对象------
2023-03-05 02:22:56 DEBUG : 请求获取账号信息接口出错，请稍后重试。错误请求信息：
{"result":-401,"error_msg":"user not login"}
2023-03-05 02:22:56 INFO  : ------结束给Acer new个对象------

2023-03-05 02:22:56 INFO  : -----随机暂停699ms-----

2023-03-05 02:22:57 INFO  : ------每日签到任务开始------
java.lang.NullPointerException
        at com.zhuweitung.task.SignTask.run(SignTask.java:19)
        at com.zhuweitung.task.DailyTask.runDailyTask(DailyTask.java:51)
        at com.zhuweitung.BananaMain.main(BananaMain.java:43)
2023-03-05 02:22:57 INFO  : 未配置消息发送通道，本次任务执行不推送

**Comment by zhuweitung** [comment]
重新获取acPasstoken并更新到secrets，a站的token一个月过期一次

**Comment by smallwhitedesu1** [comment]
> 重新获取acPasstoken并更新到secrets，a站的token一个月过期一次

![Uploading QQ截图20230306021600.png…]()
然后变这样了...
上面那个我是在本地运行的

**Comment by smallwhitedesu1** [comment]
> 重新获取acPasstoken并更新到secrets，a站的token一个月过期一次

![QQ截图20230306021600](https://user-images.githubusercontent.com/103363926/222978400-2bbbb8fb-6d0e-44c3-8788-10856d753240.png)

然后变这样了...
上面那个我是在本地运行的

**Comment by zhuweitung** [comment]
按[使用说明](https://github.com/zhuweitung/banana-helper#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)操作不会有问题
本地运行也要获取`acPassToken`和`authKey`这两个参数

**Comment by smallwhitedesu1** [comment]
> 按[使用说明](https://github.com/zhuweitung/banana-helper#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)操作不会有问题 本地运行也要获取`acPassToken`和`authKey`这两个参数

但我按[使用说明](https://github.com/zhuweitung/banana-helper#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)操作了也不行...

**Comment by zhuweitung** [comment]
![image](https://user-images.githubusercontent.com/20264596/223401357-da53438f-ad40-434d-b2c0-46ad2803804c.png)
我看你action里的[运行日志](https://github.com/smallwhitedesu1/banana-helper/actions/runs/4353031055/jobs/7606560367#step:5:31)里面就是运行参数缺失，如果你是按使用说明设置的还有问题的话，我就帮不到你了

**Comment by smallwhitedesu1** [comment]
> ![image](https://user-images.githubusercontent.com/20264596/223401357-da53438f-ad40-434d-b2c0-46ad2803804c.png) 我看你action里的[运行日志](https://github.com/smallwhitedesu1/banana-helper/actions/runs/4353031055/jobs/7606560367#step:5:31)里面就是运行参数缺失，如果你是按使用说明设置的还有问题的话，我就帮不到你了

好奇怪...

**Comment by smallwhitedesu1** [comment]
> ![image](https://user-images.githubusercontent.com/20264596/223401357-da53438f-ad40-434d-b2c0-46ad2803804c.png) 我看你action里的[运行日志](https://github.com/smallwhitedesu1/banana-helper/actions/runs/4353031055/jobs/7606560367#step:5:31)里面就是运行参数缺失，如果你是按使用说明设置的还有问题的话，我就帮不到你了

![QQ截图20230309014723](https://user-images.githubusercontent.com/103363926/223790329-eee5b05c-f277-4885-a7a3-beff251ecc21.png)
是按照[使用说明](https://github.com/zhuweitung/banana-helper#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)操作的....

**Comment by smallwhitedesu1** [comment]
> ![image](https://user-images.githubusercontent.com/20264596/223401357-da53438f-ad40-434d-b2c0-46ad2803804c.png) 我看你action里的[运行日志](https://github.com/smallwhitedesu1/banana-helper/actions/runs/4353031055/jobs/7606560367#step:5:31)里面就是运行参数缺失，如果你是按使用说明设置的还有问题的话，我就帮不到你了

这个[运行日志]是什么问题呢..
![QQ截图20230309020743333](https://user-images.githubusercontent.com/103363926/223794769-e3811774-5b72-450f-acdd-a5c81766cce6.png)

**Comment by Clackz** [comment]
你的authkey不要加下划线啊

**Comment by Clackz** [comment]
然后第二个错误是因为你把bananaPriority变量的值删掉了

**Comment by smallwhitedesu1** [comment]
> 然后第二个错误是因为你把bananaPriority变量的值删掉了

感谢 解决了
